### ISSUE TITLE
requires setting to turn off Zero RPM

### ISSUE THREAD

**Issue by wbonbon** [Rem0o/FanControl.ADLX#40] opened 2024-05-07 05:39 UTC
FanControl V188 + ADLX 0.2a

ASRock X670E Steel Legend
ASRock RX 7900 XTX Taichi

Zero RPM is always on
Since Zero RPM is turned on during calibration, calibration cannot be performed correctly.
Also, the fan starts at a high speed after the GPU temperature rises, which increases the noise.
I don't like Zero RPM so I need a setting to turn this off.

![FanControl_20240507-143720](https://github.com/Rem0o/FanControl.ADLX/assets/6835141/a90d034e-a11e-43ee-926d-b34f5455a730)

**Comment by kajoken** [comment] 2024-05-09 07:15
Did you disable the build in GPU Sensor? This helped me with the issue before.

https://github.com/Rem0o/FanControl.ADLX/issues/37#issuecomment-2081530625

Before calibration set the Tuning Control to Default again and now it should calibrate properly the next time.

Your auto curve is set to "Max fan speed" 100%. That's why it will ramp up so high. I set mine to max 60% and that was enough for me and my airflow. But yours could differ since mine is an older generation card. Oh and I'm not using Hotspot as the source but the GPU sensor. Hotspot is always higher and also effects the fan speed.

**Comment by wbonbon** [comment] 2024-05-09 07:52
I experimented with modifying the plugin
[https://github.com/wbonbon/FanControl.ADLX/commit/867986f392c39586e2a5898ce28878f15db5d603](url)
With this change, ZeroRPM should always be set to false, but for some reason ZeroRPM is turned on.

My RX7900XTX has ZeroRPM on by default, so if you do not turn off ZeroRPM with Adrenalin when calibrating with FanControl, the fan will not start and calibration will fail.

My 7900XTX is ASRock 7900XTX Taichi, so if I run the fan at 10-20% without stopping it in idle mode, there is no fan noise at all.
But if ZeroRPM is on, When the fan starts after the GPU temperature rises, I can clearly hear the noise.
I don't need ZeroRPM
For now, GPU fan control is left to Adrenalin.

![FanControl_20240509-164832](https://github.com/Rem0o/FanControl.ADLX/assets/6835141/a70371cf-f5e7-4905-ad79-bb1496907566)
![FanControl_20240509-164844](https://github.com/Rem0o/FanControl.ADLX/assets/6835141/6536a961-a6a6-4ec7-b99b-0018b2bfa160)
![FanControl_20240509-164848](https://github.com/Rem0o/FanControl.ADLX/assets/6835141/68caf909-eda8-4a7d-b1f3-58e301793531)
![RadeonSoftware_20240509-165005](https://github.com/Rem0o/FanControl.ADLX/assets/6835141/5efab2fd-fa36-418e-aeda-27816834df5f)

**Comment by Rem0o** [comment] 2024-05-09 13:34
if you look at the logic here:
![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/b3cd9e2f-9ad9-42cf-bc7c-678caa836b69)

ZeroRPM is set when FanControl ask for 0%, else zero RPM is turned off. So any % asked to the GPU but 0 will turn off ZeroRPM.  You shouldn't need to turn it on or off externally.

**Comment by nikolarun** [comment] 2024-05-15 02:12
i think you should just not use Adrenalin , then your problems go away

**Comment by Rem0o** [comment] 2024-05-15 02:26
https://github.com/Rem0o/FanControl.ADLX/assets/14118956/02319f8c-34a7-4f9a-9d42-5779d7e53c2f

Just to be clear, I recorded the behavior on my machine, which is the expected behavior. 
Changing Zero RPM from adrenaline will make FanControl lose sync of the setting.

**Comment by Nelson0213** [comment] 2024-05-19 12:04
> Github.ADLX.bug.-.Made.with.Clipchamp.mp4
> 
> Just to be clear, I recorded the behavior on my machine, which is the expected behavior. Changing Zero RPM from adrenaline will make FanControl lose sync of the setting.

Build a new system yesterday and encoutered the same problem as the op did while calibrating the gpu fan. Had to disable controll in FanControll, reset the settings in adrenalin software then can the calibration work properly. Also the fan speed will stuck at 0 occationally, can be solved using same method. But when it's working, the behavior is the same as in the video.
Didn't have this using an older version of the adrenalin software in another system several weeks ago, maybe something changed in newer version?

**Comment by wewerecreatures** [comment] 2024-06-01 16:00
I am having a similar issue. Whenever I start calibration, it sets ZeroRPM on. What I did was start calibration, immediately turn off ZeroRPM and Advanced Control, and click apply. FanControl seems to immediately turn Advanced Control on again, but NOT ZeroRPM, but upon completing calibration turns ZeroRPM on again.

**Comment by mdoss** [comment] 2024-06-14 07:50
Same exact issue. When I ran games it would use my fan curve correctly, but I noticed when I was idling that it would set my fan speed to zero despite my curve being set to always be above zero. Adrenaline 24.5.1

**Comment by kajoken** [comment] 2024-06-14 19:38
Yeah, the bug seems to be back. Just tried to setup a friends PC with a Radeon RX6950XT and we ran into the same problem like before. ZeroRPM always taking over and FanControl completely loosing the ability to control the GPU at all.

**Comment by UbikNoir** [comment] 2024-06-26 15:11
Same problem as above. I tried everything I read above. Since the last version of Fancontrol, and the latest version of ADLX, I cannot control the GPU fans

Fancontrol version: V194
ADLX version: 0.4
Adrenaline software version: 24.5.1
GPU ASUS TUF RX 6950 XT

Sometimes it works after trying multiple times, sometimes it just does not work... Like today, try as I might I cannot for the life of me make it work.
Please help.

**Comment by Rem0o** [comment] 2024-06-26 15:17
@UbikNoir  try and replicate what I do in the video here : https://github.com/Rem0o/FanControl.ADLX/issues/40#issuecomment-2111464132

What do you get? Does the ZeroRPM switch toggles like in the video?

**Comment by Rem0o** [comment] 2024-06-26 16:25
I may have found a loophole in the zeroRPM state in the plugin:

Try this build: https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

**Comment by UbikNoir** [comment] 2024-06-26 17:13
> I may have found a loophole in the zeroRPM state in the plugin:
> 
> Try this build: https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

You are awesome.... the build you provided makes the automatic calibration run successfully without zero RPM kicking in in Adrenaline!

**Comment by Rem0o** [comment] 2024-06-26 17:16
Awesome.  If others in this thread @wbonbon @purrloftruth  @Nelson0213 @mdoss  could confirm if this build here 
 https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts
 fixes the issue, will close this.

**Comment by Nelson0213** [comment] 2024-06-27 00:06
> Awesome. If others in this thread @wbonbon @purrloftruth @Nelson0213 @mdoss could confirm if this build here https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts fixes the issue, will close this.

Now It works, thank you.

**Closed** 2024-06-27 00:07 UTC

**Comment by mordang7** [comment] 2024-07-02 17:04
I can also confirm this works with the MSI RX 6800 XT GAMING Z TRIO.
