### ISSUE TITLE
Updated Adrenalin, Fan Control now instantly crashing

### ISSUE THREAD

**Issue by mjbneps** [Rem0o/FanControl.ADLX#18] opened 2023-10-28 22:56 UTC
Related to my previous thread here (https://github.com/Rem0o/FanControl.Releases/issues/1923), Fan Control again is now either not recognizing the plugin or just instantly crashing upon attempting to open. I have reinstalled Fan Control multiple times, reinstalled the same plugin files, but now it's giving me issue again. I'm not sure what the cause or fix is.

**Comment by Rem0o** [comment] 2023-12-05 18:44
Duplicate of https://github.com/Rem0o/FanControl.ADLX/issues/16

**Closed by Rem0o** 2023-12-05 18:44 UTC
